name: Build and Deploy Docker Image to ECR_back

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        node-version: '17'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: Download application.yaml from S3
      run: aws s3 cp s3://front-kko/application.yaml/application.yaml ./src/main/resources/application.yaml
      
    - name: Download Dockerfile from S3
      run: aws s3 cp s3://front-kko/Dockerfile_back ./Dockerfile

    - name: Build with Gradle
      run: ./gradlew build -x test
      
    - name: Build Docker image
      run: docker build -t ${{ secrets.ECR_REPOSITORY_URI }}/project-backend:latest .

    - name: Log in to ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Push Docker image to ECR
      run: docker push ${{ secrets.ECR_REPOSITORY_URI }}/project-backend:latest
